### ISSUE TITLE
Channel confusing in Daisy Mode

### ISSUE THREAD

**Issue by shengjiatsai** [rcassani/OpenBCI-Toolkit-LabVIEW#2] opened 2018-10-16 05:53 UTC
Hello, I test this toolkit in the 16 channel OpenBCI (Cyton+Daisy), I found that the signal from conjugate channel(channel 1 and 9, 2 and 10, ...)would arbitrary change the order.

**Comment by rcassani** [comment] 2018-10-16 20:11
At the time I developed the toolkit, I couldn't try with the Daisy extension. Does the change change in channels happens in blocks?

**Comment by shengjiatsai** [comment] 2018-10-17 03:47
I test OpenBCI (Cyton+Daisy) by 3 softwares: OpenBCI_Software(the software OpenBCI developed), LabVIEW, OpenVIBE.
The channel 1-8 on Cyton board in OpenBCI_Software and OpenVIBE are channel 1-8, 
the channel 1-8 on Daisy board in OpenBCI_Software and OpenVIBE are channel 9-16.
However, the channel 1-8 on Cyton board in the LabVIEW toolkit are always showed as channel 9-16 when I connect the Daisy board on Cyton board.(Of course the channel on Daisy is 1-8)
Even once I test , I found that the channel 3 on Cyton turn to be channel 3 , and that is abnormal, it should be channel 11. This happened twice when I test the mechine without connecting DuPont line to the conjugate channel.

**Comment by rcassani** [comment] 2018-10-17 20:08
It seems that the issue is in the `openbci_eeg_order_8ch_16ch.vi` VI. In the **"16 Channels"** case diagram, swap the 2nd and 3rd inputs of the **Build Array Function**, this should solve the problem. If it does let me know to create and upload an updated VI package with the fix

**Comment by shengjiatsai** [comment] 2018-10-25 07:41
Thanks for your reply, it works

**Comment by rcassani** [comment] 2018-10-25 17:07
The fix has been added in commit; b596dae03ce63afdbbd628ac5d2f6b9eb466af70

**Closed as completed by rcassani** 2018-10-25 17:07 UTC
